<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            ['name_ar' => 'أفغانستان', 'name_en' => 'Afghanistan', 'slug' => 'afghanistan'],
            ['name_ar' => 'ألبانيا', 'name_en' => 'Albania', 'slug' => 'albania'],
            ['name_ar' => 'الجزائر', 'name_en' => 'Algeria', 'slug' => 'algeria'],
            ['name_ar' => 'أندورا', 'name_en' => 'Andorra', 'slug' => 'andorra'],
            ['name_ar' => 'أنغولا', 'name_en' => 'Angola', 'slug' => 'angola'],
            ['name_ar' => 'أنتيغوا وباربودا', 'name_en' => 'Antigua and Barbuda', 'slug' => 'antigua-and-barbuda'],
            ['name_ar' => 'الأرجنتين', 'name_en' => 'Argentina', 'slug' => 'argentina'],
            ['name_ar' => 'أرمينيا', 'name_en' => 'Armenia', 'slug' => 'armenia'],
            ['name_ar' => 'أستراليا', 'name_en' => 'Australia', 'slug' => 'australia'],
            ['name_ar' => 'النمسا', 'name_en' => 'Austria', 'slug' => 'austria'],
            ['name_ar' => 'أذربيجان', 'name_en' => 'Azerbaijan', 'slug' => 'azerbaijan'],
            ['name_ar' => 'البهاما', 'name_en' => 'Bahamas', 'slug' => 'bahamas'],
            ['name_ar' => 'البحرين', 'name_en' => 'Bahrain', 'slug' => 'bahrain'],
            ['name_ar' => 'بنغلاديش', 'name_en' => 'Bangladesh', 'slug' => 'bangladesh'],
            ['name_ar' => 'باربادوس', 'name_en' => 'Barbados', 'slug' => 'barbados'],
            ['name_ar' => 'بيلاروسيا', 'name_en' => 'Belarus', 'slug' => 'belarus'],
            ['name_ar' => 'بلجيكا', 'name_en' => 'Belgium', 'slug' => 'belgium'],
            ['name_ar' => 'بليز', 'name_en' => 'Belize', 'slug' => 'belize'],
            ['name_ar' => 'بنين', 'name_en' => 'Benin', 'slug' => 'benin'],
            ['name_ar' => 'بوتان', 'name_en' => 'Bhutan', 'slug' => 'bhutan'],
            ['name_ar' => 'بوليفيا', 'name_en' => 'Bolivia', 'slug' => 'bolivia'],
            ['name_ar' => 'البوسنة والهرسك', 'name_en' => 'Bosnia and Herzegovina', 'slug' => 'bosnia-and-herzegovina'],
            ['name_ar' => 'بوتسوانا', 'name_en' => 'Botswana', 'slug' => 'botswana'],
            ['name_ar' => 'البرازيل', 'name_en' => 'Brazil', 'slug' => 'brazil'],
            ['name_ar' => 'بروناي', 'name_en' => 'Brunei', 'slug' => 'brunei'],
            ['name_ar' => 'بلغاريا', 'name_en' => 'Bulgaria', 'slug' => 'bulgaria'],
            ['name_ar' => 'بوركينا فاسو', 'name_en' => 'Burkina Faso', 'slug' => 'burkina-faso'],
            ['name_ar' => 'بوروندي', 'name_en' => 'Burundi', 'slug' => 'burundi'],
            ['name_ar' => 'كمبوديا', 'name_en' => 'Cambodia', 'slug' => 'cambodia'],
            ['name_ar' => 'الكاميرون', 'name_en' => 'Cameroon', 'slug' => 'cameroon'],
            ['name_ar' => 'كندا', 'name_en' => 'Canada', 'slug' => 'canada'],
            ['name_ar' => 'الرأس الأخضر', 'name_en' => 'Cape Verde', 'slug' => 'cape-verde'],
            ['name_ar' => 'جمهورية أفريقيا الوسطى', 'name_en' => 'Central African Republic', 'slug' => 'central-african-republic'],
            ['name_ar' => 'تشاد', 'name_en' => 'Chad', 'slug' => 'chad'],
            ['name_ar' => 'تشيلي', 'name_en' => 'Chile', 'slug' => 'chile'],
            ['name_ar' => 'الصين', 'name_en' => 'China', 'slug' => 'china'],
            ['name_ar' => 'كولومبيا', 'name_en' => 'Colombia', 'slug' => 'colombia'],
            ['name_ar' => 'جزر القمر', 'name_en' => 'Comoros', 'slug' => 'comoros'],
            ['name_ar' => 'كوستاريكا', 'name_en' => 'Costa Rica', 'slug' => 'costa-rica'],
            ['name_ar' => 'ساحل العاج', 'name_en' => "Côte d'Ivoire", 'slug' => 'cote-divoire'],
            ['name_ar' => 'كرواتيا', 'name_en' => 'Croatia', 'slug' => 'croatia'],
            ['name_ar' => 'كوبا', 'name_en' => 'Cuba', 'slug' => 'cuba'],
            ['name_ar' => 'قبرص', 'name_en' => 'Cyprus', 'slug' => 'cyprus'],
            ['name_ar' => 'التشيك', 'name_en' => 'Czech Republic', 'slug' => 'czech-republic'],
            ['name_ar' => 'جمهورية الكونغو الديمقراطية', 'name_en' => 'Democratic Republic of the Congo', 'slug' => 'democratic-republic-of-the-congo'],
            ['name_ar' => 'الدنمارك', 'name_en' => 'Denmark', 'slug' => 'denmark'],
            ['name_ar' => 'جيبوتي', 'name_en' => 'Djibouti', 'slug' => 'djibouti'],
            ['name_ar' => 'دومينيكا', 'name_en' => 'Dominica', 'slug' => 'dominica'],
            ['name_ar' => 'جمهورية الدومينيكان', 'name_en' => 'Dominican Republic', 'slug' => 'dominican-republic'],
            ['name_ar' => 'تيمور الشرقية', 'name_en' => 'East Timor', 'slug' => 'east-timor'],
            ['name_ar' => 'الإكوادور', 'name_en' => 'Ecuador', 'slug' => 'ecuador'],
            ['name_ar' => 'مصر', 'name_en' => 'Egypt', 'slug' => 'egypt'],
            ['name_ar' => 'السلفادور', 'name_en' => 'El Salvador', 'slug' => 'el-salvador'],
            ['name_ar' => 'غينيا الاستوائية', 'name_en' => 'Equatorial Guinea', 'slug' => 'equatorial-guinea'],
            ['name_ar' => 'إريتريا', 'name_en' => 'Eritrea', 'slug' => 'eritrea'],
            ['name_ar' => 'إستونيا', 'name_en' => 'Estonia', 'slug' => 'estonia'],
            ['name_ar' => 'إثيوبيا', 'name_en' => 'Ethiopia', 'slug' => 'ethiopia'],
            ['name_ar' => 'فيجي', 'name_en' => 'Fiji', 'slug' => 'fiji'],
            ['name_ar' => 'فنلندا', 'name_en' => 'Finland', 'slug' => 'finland'],
            ['name_ar' => 'فرنسا', 'name_en' => 'France', 'slug' => 'france'],
            ['name_ar' => 'الغابون', 'name_en' => 'Gabon', 'slug' => 'gabon'],
            ['name_ar' => 'غامبيا', 'name_en' => 'Gambia', 'slug' => 'gambia'],
            ['name_ar' => 'جورجيا', 'name_en' => 'Georgia', 'slug' => 'georgia'],
            ['name_ar' => 'ألمانيا', 'name_en' => 'Germany', 'slug' => 'germany'],
            ['name_ar' => 'غانا', 'name_en' => 'Ghana', 'slug' => 'ghana'],
            ['name_ar' => 'اليونان', 'name_en' => 'Greece', 'slug' => 'greece'],
            ['name_ar' => 'جرينادا', 'name_en' => 'Grenada', 'slug' => 'grenada'],
            ['name_ar' => 'غواتيمالا', 'name_en' => 'Guatemala', 'slug' => 'guatemala'],
            ['name_ar' => 'غينيا', 'name_en' => 'Guinea', 'slug' => 'guinea'],
            ['name_ar' => 'غينيا بيساو', 'name_en' => 'Guinea-Bissau', 'slug' => 'guinea-bissau'],
            ['name_ar' => 'غويانا', 'name_en' => 'Guyana', 'slug' => 'guyana'],
            ['name_ar' => 'هايتي', 'name_en' => 'Haiti', 'slug' => 'haiti'],
            ['name_ar' => 'هندوراس', 'name_en' => 'Honduras', 'slug' => 'honduras'],
            ['name_ar' => 'المجر', 'name_en' => 'Hungary', 'slug' => 'hungary'],
            ['name_ar' => 'آيسلندا', 'name_en' => 'Iceland', 'slug' => 'iceland'],
            ['name_ar' => 'الهند', 'name_en' => 'India', 'slug' => 'india'],
            ['name_ar' => 'إندونيسيا', 'name_en' => 'Indonesia', 'slug' => 'indonesia'],
            ['name_ar' => 'إيران', 'name_en' => 'Iran', 'slug' => 'iran'],
            ['name_ar' => 'العراق', 'name_en' => 'Iraq', 'slug' => 'iraq'],
            ['name_ar' => 'جمهورية أيرلندا', 'name_en' => 'Ireland', 'slug' => 'ireland'],
            ['name_ar' => 'فلسطين', 'name_en' => 'Palestine', 'slug' => 'palestine'],
            ['name_ar' => 'إيطاليا', 'name_en' => 'Italy', 'slug' => 'italy'],
            ['name_ar' => 'جامايكا', 'name_en' => 'Jamaica', 'slug' => 'jamaica'],
            ['name_ar' => 'اليابان', 'name_en' => 'Japan', 'slug' => 'japan'],
            ['name_ar' => 'الأردن', 'name_en' => 'Jordan', 'slug' => 'jordan'],
            ['name_ar' => 'كازاخستان', 'name_en' => 'Kazakhstan', 'slug' => 'kazakhstan'],
            ['name_ar' => 'كينيا', 'name_en' => 'Kenya', 'slug' => 'kenya'],
            ['name_ar' => 'كيريباتي', 'name_en' => 'Kiribati', 'slug' => 'kiribati'],
            ['name_ar' => 'الكويت', 'name_en' => 'Kuwait', 'slug' => 'kuwait'],
            ['name_ar' => 'قرغيزستان', 'name_en' => 'Kyrgyzstan', 'slug' => 'kyrgyzstan'],
            ['name_ar' => 'لاوس', 'name_en' => 'Laos', 'slug' => 'laos'],
            ['name_ar' => 'لاتفيا', 'name_en' => 'Latvia', 'slug' => 'latvia'],
            ['name_ar' => 'لبنان', 'name_en' => 'Lebanon', 'slug' => 'lebanon'],
            ['name_ar' => 'ليسوتو', 'name_en' => 'Lesotho', 'slug' => 'lesotho'],
            ['name_ar' => 'ليبيريا', 'name_en' => 'Liberia', 'slug' => 'liberia'],
            ['name_ar' => 'ليبيا', 'name_en' => 'Libya', 'slug' => 'libya'],
            ['name_ar' => 'ليختنشتاين', 'name_en' => 'Liechtenstein', 'slug' => 'liechtenstein'],
            ['name_ar' => 'ليتوانيا', 'name_en' => 'Lithuania', 'slug' => 'lithuania'],
            ['name_ar' => 'لوكسمبورغ', 'name_en' => 'Luxembourg', 'slug' => 'luxembourg'],
            ['name_ar' => 'مدغشقر', 'name_en' => 'Madagascar', 'slug' => 'madagascar'],
            ['name_ar' => 'مالاوي', 'name_en' => 'Malawi', 'slug' => 'malawi'],
            ['name_ar' => 'ماليزيا', 'name_en' => 'Malaysia', 'slug' => 'malaysia'],
            ['name_ar' => 'جزر المالديف', 'name_en' => 'Maldives', 'slug' => 'maldives'],
            ['name_ar' => 'مالي', 'name_en' => 'Mali', 'slug' => 'mali'],
            ['name_ar' => 'مالطا', 'name_en' => 'Malta', 'slug' => 'malta'],
            ['name_ar' => 'جزر مارشال', 'name_en' => 'Marshall Islands', 'slug' => 'marshall-islands'],
            ['name_ar' => 'موريتانيا', 'name_en' => 'Mauritania', 'slug' => 'mauritania'],
            ['name_ar' => 'موريشيوس', 'name_en' => 'Mauritius', 'slug' => 'mauritius'],
            ['name_ar' => 'المكسيك', 'name_en' => 'Mexico', 'slug' => 'mexico'],
            ['name_ar' => 'ميكرونيزيا', 'name_en' => 'Micronesia', 'slug' => 'micronesia'],
            ['name_ar' => 'مولدوفا', 'name_en' => 'Moldova', 'slug' => 'moldova'],
            ['name_ar' => 'موناكو', 'name_en' => 'Monaco', 'slug' => 'monaco'],
            ['name_ar' => 'منغوليا', 'name_en' => 'Mongolia', 'slug' => 'mongolia'],
            ['name_ar' => 'الجبل الأسود', 'name_en' => 'Montenegro', 'slug' => 'montenegro'],
            ['name_ar' => 'المغرب', 'name_en' => 'Morocco', 'slug' => 'morocco'],
            ['name_ar' => 'موزمبيق', 'name_en' => 'Mozambique', 'slug' => 'mozambique'],
            ['name_ar' => 'ميانمار', 'name_en' => 'Myanmar', 'slug' => 'myanmar'],
            ['name_ar' => 'ناميبيا', 'name_en' => 'Namibia', 'slug' => 'namibia'],
            ['name_ar' => 'ناورو', 'name_en' => 'Nauru', 'slug' => 'nauru'],
            ['name_ar' => 'نيبال', 'name_en' => 'Nepal', 'slug' => 'nepal'],
            ['name_ar' => 'هولندا', 'name_en' => 'Netherlands', 'slug' => 'netherlands'],
            ['name_ar' => 'نيوزيلندا', 'name_en' => 'New Zealand', 'slug' => 'new-zealand'],
            ['name_ar' => 'نيكاراغوا', 'name_en' => 'Nicaragua', 'slug' => 'nicaragua'],
            ['name_ar' => 'النيجر', 'name_en' => 'Niger', 'slug' => 'niger'],
            ['name_ar' => 'نيجيريا', 'name_en' => 'Nigeria', 'slug' => 'nigeria'],
            ['name_ar' => 'كوريا الشمالية', 'name_en' => 'North Korea', 'slug' => 'north-korea'],
            ['name_ar' => 'مقدونيا الشمالية', 'name_en' => 'North Macedonia', 'slug' => 'north-macedonia'],
            ['name_ar' => 'النرويج', 'name_en' => 'Norway', 'slug' => 'norway'],
            ['name_ar' => 'عُمان', 'name_en' => 'Oman', 'slug' => 'oman'],
            ['name_ar' => 'باكستان', 'name_en' => 'Pakistan', 'slug' => 'pakistan'],
            ['name_ar' => 'بالاو', 'name_en' => 'Palau', 'slug' => 'palau'],
            ['name_ar' => 'بنما', 'name_en' => 'Panama', 'slug' => 'panama'],
            ['name_ar' => 'بابوا غينيا الجديدة', 'name_en' => 'Papua New Guinea', 'slug' => 'papua-new-guinea'],
            ['name_ar' => 'باراغواي', 'name_en' => 'Paraguay', 'slug' => 'paraguay'],
            ['name_ar' => 'بيرو', 'name_en' => 'Peru', 'slug' => 'peru'],
            ['name_ar' => 'الفلبين', 'name_en' => 'Philippines', 'slug' => 'philippines'],
            ['name_ar' => 'بولندا', 'name_en' => 'Poland', 'slug' => 'poland'],
            ['name_ar' => 'البرتغال', 'name_en' => 'Portugal', 'slug' => 'portugal'],
            ['name_ar' => 'قطر', 'name_en' => 'Qatar', 'slug' => 'qatar'],
            ['name_ar' => 'جمهورية الكونغو', 'name_en' => 'Republic of the Congo', 'slug' => 'republic-of-the-congo'],
            ['name_ar' => 'رومانيا', 'name_en' => 'Romania', 'slug' => 'romania'],
            ['name_ar' => 'روسيا', 'name_en' => 'Russia', 'slug' => 'russia'],
            ['name_ar' => 'رواندا', 'name_en' => 'Rwanda', 'slug' => 'rwanda'],
            ['name_ar' => 'سانت كيتس ونيفيس', 'name_en' => 'Saint Kitts and Nevis', 'slug' => 'saint-kitts-and-nevis'],
            ['name_ar' => 'سانت لوسيا', 'name_en' => 'Saint Lucia', 'slug' => 'saint-lucia'],
            ['name_ar' => 'سانت فينسنت والغرينادين', 'name_en' => 'Saint Vincent and the Grenadines', 'slug' => 'saint-vincent-and-the-grenadines'],
            ['name_ar' => 'ساموا', 'name_en' => 'Samoa', 'slug' => 'samoa'],
            ['name_ar' => 'سان مارينو', 'name_en' => 'San Marino', 'slug' => 'san-marino'],
            ['name_ar' => 'ساو تومي وبرينسيب', 'name_en' => 'Sao Tome and Principe', 'slug' => 'sao-tome-and-principe'],
            ['name_ar' => 'السعودية', 'name_en' => 'Saudi Arabia', 'slug' => 'saudi-arabia'],
            ['name_ar' => 'السنغال', 'name_en' => 'Senegal', 'slug' => 'senegal'],
            ['name_ar' => 'صربيا', 'name_en' => 'Serbia', 'slug' => 'serbia'],
            ['name_ar' => 'سيشل', 'name_en' => 'Seychelles', 'slug' => 'seychelles'],
            ['name_ar' => 'سيراليون', 'name_en' => 'Sierra Leone', 'slug' => 'sierra-leone'],
            ['name_ar' => 'سنغافورة', 'name_en' => 'Singapore', 'slug' => 'singapore'],
            ['name_ar' => 'سلوفاكيا', 'name_en' => 'Slovakia', 'slug' => 'slovakia'],
            ['name_ar' => 'سلوفينيا', 'name_en' => 'Slovenia', 'slug' => 'slovenia'],
            ['name_ar' => 'جزر سليمان', 'name_en' => 'Solomon Islands', 'slug' => 'solomon-islands'],
            ['name_ar' => 'الصومال', 'name_en' => 'Somalia', 'slug' => 'somalia'],
            ['name_ar' => 'جنوب أفريقيا', 'name_en' => 'South Africa', 'slug' => 'south-africa'],
            ['name_ar' => 'كوريا الجنوبية', 'name_en' => 'South Korea', 'slug' => 'south-korea'],
            ['name_ar' => 'جنوب السودان', 'name_en' => 'South Sudan', 'slug' => 'south-sudan'],
            ['name_ar' => 'إسبانيا', 'name_en' => 'Spain', 'slug' => 'spain'],
            ['name_ar' => 'سريلانكا', 'name_en' => 'Sri Lanka', 'slug' => 'sri-lanka'],
            ['name_ar' => 'السودان', 'name_en' => 'Sudan', 'slug' => 'sudan'],
            ['name_ar' => 'سورينام', 'name_en' => 'Suriname', 'slug' => 'suriname'],
            ['name_ar' => 'السويد', 'name_en' => 'Sweden', 'slug' => 'sweden'],
            ['name_ar' => 'سويسرا', 'name_en' => 'Switzerland', 'slug' => 'switzerland'],
            ['name_ar' => 'سوريا', 'name_en' => 'Syria', 'slug' => 'syria'],
            ['name_ar' => 'طاجيكستان', 'name_en' => 'Tajikistan', 'slug' => 'tajikistan'],
            ['name_ar' => 'تنزانيا', 'name_en' => 'Tanzania', 'slug' => 'tanzania'],
            ['name_ar' => 'تايلاند', 'name_en' => 'Thailand', 'slug' => 'thailand'],
            ['name_ar' => 'توغو', 'name_en' => 'Togo', 'slug' => 'togo'],
            ['name_ar' => 'تونغا', 'name_en' => 'Tonga', 'slug' => 'tonga'],
            ['name_ar' => 'ترينيداد وتوباغو', 'name_en' => 'Trinidad and Tobago', 'slug' => 'trinidad-and-tobago'],
            ['name_ar' => 'تونس', 'name_en' => 'Tunisia', 'slug' => 'tunisia'],
            ['name_ar' => 'تركيا', 'name_en' => 'Turkey', 'slug' => 'turkey'],
            ['name_ar' => 'تركمانستان', 'name_en' => 'Turkmenistan', 'slug' => 'turkmenistan'],
            ['name_ar' => 'توفالو', 'name_en' => 'Tuvalu', 'slug' => 'tuvalu'],
            ['name_ar' => 'أوغندا', 'name_en' => 'Uganda', 'slug' => 'uganda'],
            ['name_ar' => 'أوكرانيا', 'name_en' => 'Ukraine', 'slug' => 'ukraine'],
            ['name_ar' => 'الإمارات العربية المتحدة', 'name_en' => 'United Arab Emirates', 'slug' => 'united-arab-emirates'],
            ['name_ar' => 'المملكة المتحدة', 'name_en' => 'United Kingdom', 'slug' => 'united-kingdom'],
            ['name_ar' => 'الولايات المتحدة', 'name_en' => 'United States', 'slug' => 'united-states'],
            ['name_ar' => 'أوروغواي', 'name_en' => 'Uruguay', 'slug' => 'uruguay'],
            ['name_ar' => 'أوزبكستان', 'name_en' => 'Uzbekistan', 'slug' => 'uzbekistan'],
            ['name_ar' => 'فانواتو', 'name_en' => 'Vanuatu', 'slug' => 'vanuatu'],
            ['name_ar' => 'فنزويلا', 'name_en' => 'Venezuela', 'slug' => 'venezuela'],
            ['name_ar' => 'فيتنام', 'name_en' => 'Vietnam', 'slug' => 'vietnam'],
            ['name_ar' => 'اليمن', 'name_en' => 'Yemen', 'slug' => 'yemen'],
            ['name_ar' => 'زامبيا', 'name_en' => 'Zambia', 'slug' => 'zambia'],
            ['name_ar' => 'زيمبابوي', 'name_en' => 'Zimbabwe', 'slug' => 'zimbabwe'],
        ];
        
        DB::table('nationalities')->insert($nationalities);
    }
}
